services:
  consumer_service_db:
    image: consumer_service_db
    build:
      context: .
      dockerfile: DatabaseConsumer/Dockerfile
    ports:
      - "5164:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_CONSUMER}
      POSTGRES_USER: ${POSTGRES_USER_CONSUMER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CONSUMER}
      POSTGRES_DB: ${POSTGRES_DB_CONSUMER}
    depends_on:
      - db-consumer
      
      
  broker-api:
    image: broker-api
    build:
      context: .
      dockerfile: BrokerApi/Dockerfile
    ports:
      - "5163:8080"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_API}
      POSTGRES_USER: ${POSTGRES_USER_API}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_API}
      POSTGRES_DB: ${POSTGRES_DB_API}
    depends_on:
      - db-broker-api

  db-broker-api:
    image: postgres:latest
    container_name: db-broker-api
    ports:
      - "5438:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_API}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_API}
      POSTGRES_DB: ${POSTGRES_DB_API}
  
  db-consumer:
    image: postgres:latest
    container_name: db-consumer
    ports:
      - "5439:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER_CONSUMER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_CONSUMER}
      POSTGRES_DB: ${POSTGRES_DB_CONSUMER}
      
  consumer-bot:
    image: consumer-bot
    build:
      context: .
      dockerfile: TelegramConsumer/Dockerfile
    ports:
      - "5165:8080"
    env_file:
      - .env
    depends_on:
      - broker-api
  
  console-producer:
    image: console-producer
    build:
      context: .
      dockerfile: ConsoleProducer/Dockerfile
    env_file:
      - .env
    depends_on:
      - broker-api